version: '3.4'

services:

  postgres:
    image: postgres:13-alpine
    ports:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=notes_db
      - PGDATA=/var/lib/postgresql-static/data
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql

  notes-app:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        WORKDIR: ${PWD}
    volumes:
      - ".:${PWD}:delegated"
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
